#page information
title: djzdjzdl's Blog.
name: Coder, Learner
description: Learning Something
url: https://djzdjzdl.gitjub.io
#url: http://127.0.0.1:4000
email: a272714@naver.com
  
header_pages:
  - index.md
  - about.md
  - study.md
  - contact.md

pages:
  - Pwnables.md
  - Reversing.md
  - WebHacking.md
  - CryptoGraphy.md
  - Forensics.md

#twitter_username: djzdjzdl
#github_username:  djzdjzdl

#Language, Timezone setting
encoding: "utf-8"
lang: ko
timezone: Asia/Seoul

style: dark
listen_for_clients_preferred_style: false # false (default) or true 이 부분으로 github에 적용됨
footer: 'follow me on <a href="https://bcglab.jbnu.ac.kr">BCG Labs</a>'
google_analytics: UA-NNNNNNNN-N

disqus_shortname: https-djzdjzdl-github-io-1

# Build settings
remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag